### ISSUE TITLE
MDX Debugger not able to open up MDX Calculations script 

### ISSUE THREAD

**Issue by cosminioan** [gbrueckl/AnalysisServices.MDXScriptDebugger#1]
hi Gerhard, 
I've come across a project that requires some debugging using your great tool MDXDebugger, but when trying to kick it off on an SSAS 2017 CU15 on my own desktop, I get  "Errors in the metadata manager.  Either the cube with the ID of 'xxx' does not exist in the database with the ID of "yyy', or the user does not have permissions to access the object.  I've even pared down the big CALCULATIONS script to just a handful of calcs and still no luck.  Not sure what's going on, perhaps it does not work with SSAS 2017 Multidimensional?

many thanks for any thoughts,
Cos

**Comment by gbrueckl** [comment]
Hi Cos,
It was at least never tested with SSAS 2017. In fact the last time I was working on it was back with 2012 or 2014.
You can try to download the source and use the DLLs from 2017 to find the root cause of the issue.
Unfortunately I have very limited time at the moment, sorry! 

Regards, 
-gerhard

**Comment by cosminioan** [comment]
Thanks bunches for the fast response, yes, I will tinker with it and let you know. 
Thanks again!! Cos

Sent from Yahoo Mail on Android 
 
  On Tue, Sep 17, 2019 at 1:25 PM, Gerhard Brueckl<notifications@github.com> wrote:   
Hi Cos,
It was at least never tested with SSAS 2017. In fact the last time I was working on it was back with 2012 or 2014.
You can try to download the source and use the DLLs from 2017 to find the root cause of the issue.
Unfortunately I have very limited time at the moment, sorry!

Regards,
-gerhard

**Comment by cosminioan** [comment]
it turned out, my cubeId and cubeName are different from one another (not the databasename/databaseid),  so I have to figure out next how to align the old CubeID with the new CubeName  :-)  and I believe everything should work fine as I tested with AdventureWorks 2017 and everything is working fine.  Many thanks for the wonderful tool, Gerhard.
